---
# This playbook deploys the entire OpenStack install


- name: Setup and Configure Common Elements for controller
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - keystone
    - glance
    - nova
    - common
    - os_setup

  roles:
    - common

- name: Setup and Configure Common Elements for network
  hosts: network
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - common
    - neutron

  roles:
    - common

- name: Setup and Configure Common Elements for compute
  hosts: compute
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - common
    - nova

  roles:
    - common

- name: Deploy and Configure the OS Database
  hosts: db
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - db
    - os_setup

  roles:
    - db

- name: Deploy and Configure the OS MQ
  hosts: mq
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - mq
    - rabbit
    - rabbitmq
    - os_setup

  roles:
    - mq

- name: Deploy and Configure the Identity Service
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags: keystone

  roles:
    - keystone

- name: Deploy and Configure the Image Service
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags: glance

  roles:
    - glance

- name: Deploy and Configure the Compute Service (controller part)
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - nova
    - nova_controller

  roles:
    - nova_controller

- name: Deploy and Configure the Compute Service (compute part)
  hosts: compute
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - nova
    - nova_compute

  roles:
    - nova_compute

- name: Deploy and Configure the Networking Service (controller part)
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - neutron
    - neutron_controller

  roles:
    - neutron_controller

- name: Deploy and Configure the Networking Service (network part)
  hosts: network
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - neutron
    - neutron_network

  roles:
    - neutron_network

- name: Deploy and Configure the Networking Service (compute part)
  hosts: compute
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - neutron
    - neutron_compute

  roles:
    - neutron_compute

- name: Create Networks
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - neutron
    - network_create

  roles:
    - network_create

- name: Deploy and Configure the Dashboard Service (controller)
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - horizon

  roles:
    - horizon

- name: Deploy and Configure the Block Storage Service (controller part)
  hosts: controller
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - cinder
    - cinder_controller

  roles:
    - cinder_controller

- name: Deploy and Configure the Block Storage Service (compute part)
  hosts: compute
  user: "{{ remote_user }}"
  vars_files:
    - custom_vars.yml
  tags:
    - cinder
    - cinder_compute

  roles:
    - cinder_compute

