---

- name: restart neutron network
  service: name={{ item }} state=restarted
  with_items:
    - nova-compute
    - openvswitch-switch
    - neutron-plugin-openvswitch-agent

- name: reload sysctl
  command: sysctl -p
