
- name: Make sure we have a conf directory
  file: dest={{ conf_dir }}
        state=directory
        owner=swift
        group=swift
        mode=0775

- name: Configure hash
  template: src={{ conf_name }}.j2
            dest={{ conf_file }}
            owner=swift
            group=swift
            mode=0664

