---

- name: Create swift user
  shell: creates={{ swift_user_created }}
         /usr/bin/keystone --os-token={{ service_token }} --os-endpoint={{ service_endpoint }} user-create --name=swift --pass={{ swift_pass }} --email=swift_email@example.com
- name: Mark swift user as created
  lineinfile: dest={{ swift_user_created }}
              line=done
              state=present
              create=yes

- name: Add swift admin role
  shell: creates={{ swift_admin_role }}
         /usr/bin/keystone --os-token={{ service_token }} --os-endpoint={{ service_endpoint }} user-role-add --user=swift --tenant=service --role=admin
- name: Mark swift admin roll as added
  lineinfile: dest={{ swift_admin_role }}
              line=done
              state=present
              create=yes

- name: Create Object Storage service
  shell: creates={{ swift_service_created }}
         /usr/bin/keystone --os-token={{ service_token }} --os-endpoint={{ service_endpoint }} service-create --name=swift --type=object-store --description="OpenStack Object Storage"
- name: Mark object storage service as created
  lineinfile: dest={{ swift_service_created }}
              line=done
              state=present
              create=yes

- name: Get the Object Storage service id
  shell: creates={{ swift_endpoint_created }}
         /usr/bin/keystone --os-token={{ service_token }} --os-endpoint={{ service_endpoint }} service-list | awk '/ object-store / {print $2}'
  register: swift_service_id
- name: Create object storage endpoint
  shell: creates={{ swift_endpoint_created }}
         /usr/bin/keystone --os-token={{ service_token }} --os-endpoint={{ service_endpoint }} endpoint-create --service-id={{ swift_service_id['stdout_lines'][0] }} --publicurl=http://controller:8080/v1/AUTH_%\(tenant_id\)s --internalurl=http://controller:8080/v1/AUTH_%\(tenant_id\)s --adminurl=http://controller:8080
- name: Mark object storage endpoint as created
  lineinfile: dest={{ swift_endpoint_created }}
              line=done
              state=present
              create=yes

