---

- name: Start swift services
  service: name={{ item }} state=started
  with_items:
    - swift-object
    - swift-object-replicator
    - swift-object-updater
    - swift-object-auditor
    - swift-container
    - swift-container-replicator
    - swift-container-updater
    - swift-container-auditor
    - swift-account
    - swift-account-replicator
    - swift-account-reaper
    - swift-account-auditor

