---

- name: Push swift rings to compute
  copy: src=../../../{{ fetch_dir }}/{{ controller_ext_ip }}/{{ conf_dir }}/{{ item }} dest={{ conf_dir }}/{{ item }} mode=0664
  with_items:
    - "account.ring.gz"
    - "container.ring.gz"
    - "object.ring.gz"
  notify: restart swift compute start

- name: Change permissions on {{ conf_dir }}
  file: dest={{ conf_dir }} state=directory recurse=yes owner=swift group=swift
  notify: restart swift compute start

- name: Start swift services
  service: name={{ item }} state=started
  with_items:
    - swift-object
    - swift-object-replicator
    - swift-object-updater
    - swift-object-auditor
    - swift-container
    - swift-container-replicator
    - swift-container-updater
    - swift-container-auditor
    - swift-account
    - swift-account-replicator
    - swift-account-reaper
    - swift-account-auditor

