---

- name: Install nova Compute service on controller
  apt: name={{ item }} state=present
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - python-novaclient

- name: Remove sqllite db
  file: path=/var/lib/nova/nova.sqlite
        state=absent

- name: Make sure default section exists in conf files
  lineinfile: dest={{ item }}
              regexp="^(\[default\]|\[DEFAULT\])$"
              insertbefore=BOF
              line=[DEFAULT]
              backup=yes
              create=yes
  with_items:
    - "{{ conf_file }}"
  notify: restart nova controller

- name: Configure db conn
  ini_file: dest={{ item[0] }}
            section=database
            option={{item[1].option}}
            value={{item[1].value}}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: connection, value: "mysql://nova:{{ nova_dbpass }}@controller/nova"},
      ]
  notify: restart nova controller

- name: Configure rabbit rpc
  ini_file: dest={{ item[0] }}
            section=DEFAULT
            option={{ item[1].option }}
            value={{ item[1].value }}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: rpc_backend, value: rabbit},
      {option: rabbit_host, value: controller},
      {option: rabbit_password, value: "{{ rabbit_pass }}"},
      ]
  notify: restart nova controller

- name: Configure IPs
  ini_file: dest={{ item[0] }}
            section=DEFAULT
            option={{ item[1].option }}
            value={{ item[1].value }}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: my_ip, value: "{{ controller_mgmt_ip }}"},
      {option: vncserver_listen, value: "{{ controller_mgmt_ip }}"},
      {option: vncserver_proxyclient_address, value: "{{ controller_mgmt_ip }}"},
      ]
  notify: restart nova controller

- name: Configure keystone authtoken
  ini_file: dest={{ item[0] }}
            section=keystone_authtoken
            option={{item[1].option}}
            value={{item[1].value}}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: auth_uri, value: "http://controller:5000"},
      {option: auth_host, value: controller},
      {option: auth_port, value: 35357},
      {option: auth_protocol, value: http},
      {option: admin_tenant_name, value: service},
      {option: admin_user, value: nova},
      {option: admin_password, value: "{{ nova_pass }}"},
      ]
  notify: restart nova controller

- name: Configure strategy
  ini_file: dest={{ item[0] }}
            section=DEFAULT
            option={{item[1].option}}
            value={{item[1].value}}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: auth_strategy, value: keystone},
      ]
  notify: restart nova controller

# until a way to trigger the notify's after a task is done is found,
# this'll have to do - we need to restart before the next task starts
- name: Restart nova controller
  shell: creates={{ nova_controller_restarted }}
         service {{ item }} restart
  with_items:
    - nova-api
    - nova-cert
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
- name: Mark nova controller restarted
  lineinfile: dest={{ nova_controller_restarted }}
              line=done
              state=present
              create=yes

