---

- name: Create neutron database
  mysql_db: db=neutron
            state=present
            encoding=utf8
            login_user={{ mysql_root_user }}
            login_password={{ mysql_root_password }}
  notify: restart neutron controller

- name: Grant access to neutron user
  mysql_user: login_user={{ mysql_root_user }}
              login_password={{ mysql_root_password }}
              login_port=3306
              state=present
              name=neutron
              password={{ neutron_dbpass }}
              host={{ item }}
              priv=neutron.*:ALL,GRANT
  with_items:
    - localhost
    - "%"
  notify: restart neutron controller

