---

- name: Create nova database
  mysql_db: db=nova
            state=present
            encoding=utf8
            login_user={{ mysql_root_user }}
            login_password={{ mysql_root_password }}

- name: Grant access to nova user
  mysql_user: login_user={{ mysql_root_user }}
              login_password={{ mysql_root_password }}
              login_port=3306
              state=present
              name=nova
              password={{ nova_dbpass }}
              host={{ item }}
              priv=nova.*:ALL,GRANT
  with_items:
  - localhost
  - "%"
  notify:
  - restart nova

- name: Create nova tables
  shell: creates={{ nova_tables_created }}
         su -s /bin/sh -c "nova-manage db sync" nova
  
- name: Mark tables as created
  lineinfile: dest={{ nova_tables_created }}
              line=done
              state=present
              create=yes


