---

- name: Install cinder Block Volume service on controller
  apt: name={{ item }} state=present
  with_items:
    - cinder-api
    - cinder-scheduler

- name: Make sure default section exists in conf files
  lineinfile: dest={{ item }}
              regexp="^(\[default\]|\[DEFAULT\])$"
              insertbefore=BOF
              line=[DEFAULT]
              backup=yes
              create=yes
  with_items:
    - "{{ conf_file }}"
  notify: restart cinder controller

- name: Configure db conn
  ini_file: dest={{ item[0] }}
            section=database
            option={{item[1].option}}
            value={{item[1].value}}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: connection, value: "mysql://cinder:{{ cinder_dbpass }}@controller/cinder"},
      ]
  notify: restart cinder controller

# This wasn't in the instructions, so I'm leaving it out
#- name: Configure strategy
#  ini_file: dest={{ item[0] }}
#            section=DEFAULT
#            option={{item[1].option}}
#            value={{item[1].value}}
#            backup=yes
#  with_nested:
#    - ["{{ conf_file }}"]
#    - [
#      {option: auth_strategy, value: keystone},
#      ]
#  notify: restart cinder controller

- name: Configure keystone authtoken
  ini_file: dest={{ item[0] }}
            section=keystone_authtoken
            option={{item[1].option}}
            value={{item[1].value}}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: auth_uri, value: "http://controller:5000"},
      {option: auth_host, value: controller},
      {option: auth_port, value: 35357},
      {option: auth_protocol, value: http},
      {option: admin_tenant_name, value: service},
      {option: admin_user, value: cinder},
      {option: admin_password, value: "{{ cinder_pass }}"},
      ]
  notify: restart cinder controller

- name: Configure rabbit rpc
  ini_file: dest={{ item[0] }}
            section=DEFAULT
            option={{ item[1].option }}
            value={{ item[1].value }}
            backup=yes
  with_nested:
    - ["{{ conf_file }}"]
    - [
      {option: rpc_backend, value: cinder.openstack.common.rpc.impl_kombu},
      {option: rabbit_host, value: controller},
      {option: rabbit_port, value: 5672},
      {option: rabbit_userid, value: guest},
      {option: rabbit_password, value: "{{ rabbit_pass }}"},
      ]
  notify: restart cinder controller

