---
# This playbook will install mysql and create db user and give permissions.

- name: Debug vars
  debug: var=mysql_root_user

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Update root password
  mysql_user: login_user={{ mysql_root_user }}
              login_password={{ mysql_root_password }}
              login_port=3306
              state=present
              name={{ mysql_root_user }}
              password={{ mysql_root_password }}
              host={{ item }}
              priv=*.*:ALL,GRANT
              check_implicit_admin=true
  with_items:
    - localhost
    - "%"
  notify: restart mysql

- name: Configure db
  lineinfile: dest={{ item }}
              regexp="bind-address"
              insertafter="\[mysqld\]"
              line="bind-address            = {{ controller_mgmt_ip  }}"
              backup=yes
              create=yes
  with_items:
    - "{{ conf_file }}"
  notify: restart mysql

- name: Restart Mysql Service
  service: name=mysql state=restarted enabled=true

# until a way to trigger the notify's after a task is done is found,
# this'll have to do - we need to restart before the next task starts
- name: Restart MySQL Service
  shell: creates={{ mysql_restarted }}
         service {{ item }} restart
  with_items: mysql
- name: Mark MySQL restarted
  lineinfile: dest={{ mysql_restarted }}
              line=done
              state=present
              create=yes

