---

# Only run "update_cache=yes" if the last one is more than more than 3600 seconds ago
- apt: update_cache=yes cache_valid_time=3600
  tags: dist_current

# Update all packages to the latest version
- apt: upgrade=dist
  tags: dist_current

