---

- name: restart neutron controller
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - neutron-server
# this one may not be necessary
    - neutron-plugin-ml2

