---

- name: Create keystone database
  mysql_db: db=keystone
            state=present
            encoding=utf8
            login_user={{ mysql_root_user }}
            login_password={{ mysql_root_password }}
  notify: restart keystone

- name: Grant access to keystone user
  mysql_user: login_user={{ mysql_root_user }}
              login_password={{ mysql_root_password }}
              login_port=3306
              state=present
              name=keystone
              password={{ keystone_dbpass }}
              host={{ item }}
              priv=keystone.*:ALL,GRANT
  with_items:
    - localhost
    - "%"
  notify: restart keystone

- name: Create keystone tables
  shell: creates={{ keystone_tables_created }}
         su -s /bin/sh -c "keystone-manage db_sync" keystone
  notify: restart keystone
- name: Mark tables as created
  lineinfile: dest={{ keystone_tables_created }}
              line=done
              state=present
              create=yes

